// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"nekowindow-backend/app/{{cookiecutter.kind}}/{{cookiecutter.department}}/{{cookiecutter.service_name}}/internal/biz"
	"nekowindow-backend/app/{{cookiecutter.kind}}/{{cookiecutter.department}}/{{cookiecutter.service_name}}/internal/conf"
	"nekowindow-backend/app/{{cookiecutter.kind}}/{{cookiecutter.department}}/{{cookiecutter.service_name}}/internal/data"
	"nekowindow-backend/app/{{cookiecutter.kind}}/{{cookiecutter.department}}/{{cookiecutter.service_name}}/internal/server"
	"nekowindow-backend/app/{{cookiecutter.kind}}/{{cookiecutter.department}}/{{cookiecutter.service_name}}/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	discovery := server.NewDiscovery(registry)
	identifyClient := data.NewIdentifyClient(discovery)
	dataData, cleanup, err := data.NewData(confData, identifyClient, logger)
	if err != nil {
		return nil, nil, err
	}
	{{cookiecutter.service_name}}Repo := data.New{{cookiecutter.serviceUpper}}Repo(dataData, logger)
	identifyRepo := data.NewIdentifyRepo(dataData, logger)
	{{cookiecutter.service_name}}Usecase := biz.New{{cookiecutter.serviceUpper}}Usecase({{cookiecutter.service_name}}Repo, identifyRepo, logger)
	{{cookiecutter.service_name}}Service := service.New{{cookiecutter.serviceUpper}}Service({{cookiecutter.service_name}}Usecase, logger)
	httpServer := server.NewHTTPServer(confServer, {{cookiecutter.service_name}}Service, logger)
	grpcServer := server.NewGRPCServer(confServer, {{cookiecutter.service_name}}Service, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
